---
name: Release Please

"on":
  workflow_dispatch:
  push:
    branches:
      - staging

concurrency:
  group: release-please
  cancel-in-progress: false

jobs:
  release-please:
    name: Release Please
    outputs:
      manifest: ${{ toJSON(steps.rp.outputs) }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate App Token
        uses: tibdex/github-app-token@v1
        id: generate-token
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Release Please
        id: rp
        uses: googleapis/release-please-action@v4.1.3
        with:
          token: ${{ steps.generate-token.outputs.token }}
  matrix:       
    if: ${{ fromJSON(needs.release-please.outputs.manifest).releases_created == 'true' }}
    needs: [release-please]
    secrets: inherit
    strategy:
      matrix:
        path: ${{ fromJSON(fromJSON(needs.release-please.outputs.manifest).paths_released) }}
    uses: ./.github/workflows/build-staging.yaml
    with:
      path: ${{ matrix.path }}